[phases.install]
cmds = ["pip install -r requirements.txt"]

[variables]
PYTHONPATH = "/app/src"

[start]
cmd = "PYTHONPATH=/app/src python -m akinator.seed && PYTHONPATH=/app/src python -m akinator"
